FROM microsoft/aspnetcore-build:2.0

LABEL maintainer="drprado2@gmail.com" 

RUN mkdir projects && mkdir publish

ADD ./app /projects/

WORKDIR /projects

RUN dotnet restore -v minimal && dotnet publish --output /publish/


