FROM nginx:alpine

RUN cd /usr/local/sbin &&\
 wget https://dl.eff.org/certbot-auto &&\
  chmod a+x /usr/local/sbin/certbot-auto

RUN mkdir /var/www/meu-projeto && cp /usr/share/nginx/html/* /var/www/meu-projeto\
    && rm /etc/nginx/conf.d/default.conf

ADD ./config/nginx/default.conf /etc/nginx/conf.d/

CMD ["nginx", "-g", "daemon off;"]
